export const SITE = {
  name: 'RecipeCrave',
  tagline: 'AI cooking coach that turns what you have into what you crave.',
  description:
    'Free AI-powered recipe discovery, meal planning, and step-by-step cooking with calories, costs, and pantry-aware suggestions. The smartest free cooking app on the web.',
  // Canonical site URL — must match the actual served host (www, not apex)
  // since apex redirects 307 -> www. If you ever move off Vercel/Cloudflare,
  // update both this constant AND the env var on the new host.
  url: 'https://www.recipecrave.com',
  ogImage: '/opengraph-image',
  twitter: '@recipecrave',
  email: 'recipecravee@gmail.com',
  publisher: 'RecipeCrave',
  founded: '2026',
} as const;

export const CUISINES = [
  { slug: 'nigerian', name: 'Nigerian', emoji: '🍲' },
  { slug: 'ghanaian', name: 'Ghanaian', emoji: '🥘' },
  { slug: 'jamaican', name: 'Jamaican', emoji: '🌶️' },
  { slug: 'west-african', name: 'West African', emoji: '🍛' },
  { slug: 'italian', name: 'Italian', emoji: '🍝' },
  { slug: 'mexican', name: 'Mexican', emoji: '🌮' },
  { slug: 'indian', name: 'Indian', emoji: '🍛' },
  { slug: 'chinese', name: 'Chinese', emoji: '🥡' },
  { slug: 'japanese', name: 'Japanese', emoji: '🍱' },
  { slug: 'thai', name: 'Thai', emoji: '🍜' },
  { slug: 'mediterranean', name: 'Mediterranean', emoji: '🥗' },
  { slug: 'american', name: 'American', emoji: '🍔' },
  { slug: 'french', name: 'French', emoji: '🥐' },
  { slug: 'middle-eastern', name: 'Middle Eastern', emoji: '🧆' },
  { slug: 'korean', name: 'Korean', emoji: '🍚' },
  { slug: 'vietnamese', name: 'Vietnamese', emoji: '🍲' },
  { slug: 'caribbean', name: 'Caribbean', emoji: '🍹' },
  { slug: 'spanish', name: 'Spanish', emoji: '🥘' },
  { slug: 'greek', name: 'Greek', emoji: '🫒' },
  { slug: 'south-african', name: 'South African', emoji: '🍖' },
  { slug: 'ethiopian', name: 'Ethiopian', emoji: '🍛' },
  { slug: 'brazilian', name: 'Brazilian', emoji: '🥩' },
  { slug: 'russian', name: 'Russian', emoji: '🥟' },
  { slug: 'canadian', name: 'Canadian', emoji: '🍁' },
  { slug: 'indonesian', name: 'Indonesian', emoji: '🍚' },
  { slug: 'german', name: 'German', emoji: '🥨' },
  { slug: 'turkish', name: 'Turkish', emoji: '🌯' },
  { slug: 'polish', name: 'Polish', emoji: '🥟' },
  { slug: 'argentinian', name: 'Argentinian', emoji: '🥩' },
  { slug: 'peruvian', name: 'Peruvian', emoji: '🌶️' },
  { slug: 'egyptian', name: 'Egyptian', emoji: '🫓' },
  { slug: 'australian', name: 'Australian', emoji: '🦘' },
  // === Asia + Pacific expansion ===
  { slug: 'filipino', name: 'Filipino', emoji: '🇵🇭' },
  { slug: 'malaysian', name: 'Malaysian', emoji: '🥥' },
  { slug: 'singaporean', name: 'Singaporean', emoji: '🍤' },
  { slug: 'pakistani', name: 'Pakistani', emoji: '🍛' },
  { slug: 'sri-lankan', name: 'Sri Lankan', emoji: '🌶️' },
  { slug: 'nepalese', name: 'Nepalese', emoji: '🥟' },
  { slug: 'burmese', name: 'Burmese', emoji: '🍜' },
  { slug: 'cambodian', name: 'Cambodian', emoji: '🍚' },
  { slug: 'mongolian', name: 'Mongolian', emoji: '🍖' },
  // === Middle East + North Africa expansion ===
  { slug: 'persian', name: 'Persian', emoji: '🍢' },
  { slug: 'lebanese', name: 'Lebanese', emoji: '🥙' },
  { slug: 'moroccan', name: 'Moroccan', emoji: '🍲' },
  { slug: 'tunisian', name: 'Tunisian', emoji: '🌶️' },
  { slug: 'israeli', name: 'Israeli', emoji: '🧆' },
  // === Africa expansion ===
  { slug: 'kenyan', name: 'Kenyan', emoji: '🍖' },
  { slug: 'senegalese', name: 'Senegalese', emoji: '🍛' },
  { slug: 'ivorian', name: 'Ivorian', emoji: '🍲' },
  // === Latin America + Caribbean expansion ===
  { slug: 'cuban', name: 'Cuban', emoji: '🥘' },
  { slug: 'dominican', name: 'Dominican', emoji: '🍌' },
  { slug: 'colombian', name: 'Colombian', emoji: '☕' },
  { slug: 'venezuelan', name: 'Venezuelan', emoji: '🌮' },
  { slug: 'chilean', name: 'Chilean', emoji: '🌶️' },
  // === Europe expansion ===
  { slug: 'portuguese', name: 'Portuguese', emoji: '🍷' },
  { slug: 'british', name: 'British', emoji: '🫖' },
  { slug: 'irish', name: 'Irish', emoji: '☘️' },
  { slug: 'hungarian', name: 'Hungarian', emoji: '🌶️' },
  { slug: 'ukrainian', name: 'Ukrainian', emoji: '🥟' },
  { slug: 'austrian', name: 'Austrian', emoji: '🥨' },
  { slug: 'belgian', name: 'Belgian', emoji: '🍫' },
  // === North America regional ===
  { slug: 'hawaiian', name: 'Hawaiian', emoji: '🍍' },
  { slug: 'cajun', name: 'Cajun', emoji: '🌶️' },
  { slug: 'soul-food', name: 'Soul Food', emoji: '🍗' },
  { slug: 'tex-mex', name: 'Tex-Mex', emoji: '🌯' },
] as const;

export const COURSES_NAV = [
  { slug: 'breakfast', name: 'Breakfast', emoji: '🥞' },
  { slug: 'lunch', name: 'Lunch', emoji: '🥪' },
  { slug: 'dinner', name: 'Dinner', emoji: '🍽️' },
  { slug: 'appetizer', name: 'Small Chops & Appetizers', emoji: '🥟' },
  { slug: 'soup', name: 'Soups & Stews', emoji: '🍲' },
  { slug: 'salad', name: 'Salads', emoji: '🥗' },
  { slug: 'side', name: 'Sides', emoji: '🍚' },
  { slug: 'snack', name: 'Snacks', emoji: '🍿' },
  { slug: 'dessert', name: 'Cakes & Desserts', emoji: '🍰' },
  { slug: 'pastry', name: 'Pastries & Baking', emoji: '🥐' },
  { slug: 'smoothie', name: 'Smoothies', emoji: '🥤' },
  { slug: 'drink', name: 'Drinks & Cocktails', emoji: '🍹' },
] as const;

export const DIETS = [
  { slug: 'vegetarian', name: 'Vegetarian', schema: 'VegetarianDiet' },
  { slug: 'vegan', name: 'Vegan', schema: 'VeganDiet' },
  { slug: 'gluten-free', name: 'Gluten-Free', schema: 'GlutenFreeDiet' },
  { slug: 'dairy-free', name: 'Dairy-Free', schema: 'LowLactoseDiet' },
  { slug: 'keto', name: 'Keto', schema: 'LowCarbohydrateDiet' },
  { slug: 'paleo', name: 'Paleo', schema: 'LowCarbohydrateDiet' },
  { slug: 'low-carb', name: 'Low-Carb', schema: 'LowCarbohydrateDiet' },
  { slug: 'low-calorie', name: 'Low-Calorie', schema: 'LowCalorieDiet' },
  { slug: 'low-fat', name: 'Low-Fat', schema: 'LowFatDiet' },
  { slug: 'low-sodium', name: 'Low-Sodium', schema: 'LowSaltDiet' },
  { slug: 'high-protein', name: 'High-Protein', schema: 'LowCalorieDiet' },
  { slug: 'diabetic', name: 'Diabetic-Friendly', schema: 'DiabeticDiet' },
  { slug: 'halal', name: 'Halal', schema: 'HalalDiet' },
  { slug: 'kosher', name: 'Kosher', schema: 'KosherDiet' },
  // === Lifestyle + clinical-style diets ===
  { slug: 'mediterranean-diet', name: 'Mediterranean Diet', schema: 'LowCalorieDiet' },
  { slug: 'dash-diet', name: 'DASH Diet (heart-healthy)', schema: 'LowSaltDiet' },
  { slug: 'whole30', name: 'Whole30', schema: 'LowCarbohydrateDiet' },
  { slug: 'pescatarian', name: 'Pescatarian', schema: 'VegetarianDiet' },
  { slug: 'flexitarian', name: 'Flexitarian', schema: 'VegetarianDiet' },
  { slug: 'low-fodmap', name: 'Low-FODMAP (IBS-friendly)', schema: 'LowCalorieDiet' },
  { slug: 'anti-inflammatory', name: 'Anti-Inflammatory', schema: 'LowCalorieDiet' },
  { slug: 'plant-based', name: 'Plant-Based', schema: 'VegetarianDiet' },
  { slug: 'nut-free', name: 'Nut-Free (allergy-safe)', schema: 'LowCalorieDiet' },
  { slug: 'pregnancy-safe', name: 'Pregnancy-Safe', schema: 'LowCalorieDiet' },
] as const;

export const COURSES = [
  'breakfast',
  'brunch',
  'lunch',
  'dinner',
  'appetizer',
  'side',
  'soup',
  'salad',
  'snack',
  'dessert',
  'pastry',
  'smoothie',
  'drink',
  'sauce',
] as const;

export const OCCASIONS = [
  'weeknight',
  'date-night',
  'meal-prep',
  'game-day',
  'thanksgiving',
  'christmas',
  'easter',
  'birthday',
  'potluck',
  'picnic',
  'summer-grilling',
  'comfort-food',
] as const;

export const NAV_LINKS = [
  { href: '/recipes', label: 'Recipes' },
  { href: '/categories', label: 'Categories' },
  { href: '/collections', label: 'Collections' },
  { href: '/meal-planner', label: 'Meal Planner' },
  { href: '/pantry-match', label: "What's In My Fridge" },
  { href: '/how-to', label: 'How-To' },
] as const;
