import type { Recipe } from '@/types/recipe';

// Twelve original launch recipes — concise, complete, schema.org-ready.
// Used to seed the database and render the homepage before the AI batch
// generator runs.

const now = new Date().toISOString();

function base(slug: string): Pick<Recipe, 'id' | 'slug' | 'publishedAt' | 'updatedAt' | 'authorId' | 'isAiAssisted' | 'isPublished' | 'viewCount' | 'saveCount' | 'cookCount' | 'avgRating' | 'ratingCount'> {
  return {
    id: slug,
    slug,
    publishedAt: now,
    updatedAt: now,
    authorId: null,
    isAiAssisted: false,
    isPublished: true,
    viewCount: 0,
    saveCount: 0,
    cookCount: 0,
    avgRating: 4.8,
    ratingCount: 12,
  };
}

export const SEED_RECIPES: Recipe[] = [
  {
    ...base('one-pan-lemon-garlic-chicken'),
    title: 'One-Pan Lemon Garlic Chicken',
    description:
      'Crispy-skinned chicken thighs roasted with lemon, garlic, and herbs on a sheet of golden potatoes — twenty minutes of prep, one pan to clean.',
    heroImage: null,
    galleryImages: [],
    videoUrl: null,
    prepTimeMin: 15,
    cookTimeMin: 35,
    totalTimeMin: 50,
    servings: 4,
    difficulty: 'easy',
    cuisine: 'mediterranean',
    course: 'dinner',
    occasion: 'weeknight',
    equipment: ['Sheet pan', 'Oven'],
    ingredients: [
      { name: 'bone-in chicken thighs', qty: 8, unit: 'pieces' },
      { name: 'baby potatoes, halved', qty: 1.5, unit: 'lb' },
      { name: 'lemon, sliced', qty: 1, unit: 'whole' },
      { name: 'garlic cloves, smashed', qty: 6, unit: 'cloves' },
      { name: 'olive oil', qty: 3, unit: 'tbsp' },
      { name: 'dried oregano', qty: 1, unit: 'tsp' },
      { name: 'kosher salt', qty: 1, unit: 'tsp' },
      { name: 'black pepper', qty: 0.5, unit: 'tsp' },
      { name: 'fresh parsley, chopped', qty: 2, unit: 'tbsp' },
    ],
    instructions: [
      { step: 1, text: 'Heat oven to 425°F (220°C). Pat chicken thighs very dry — this is the difference between crispy and steamed.' },
      { step: 2, text: 'Toss potatoes, garlic, lemon slices, oil, oregano, salt, and pepper on a sheet pan. Push to the edges.' },
      { step: 3, text: 'Place chicken skin-side up in the center. Season skin with salt.' },
      { step: 4, text: 'Roast 30–35 minutes until chicken hits 165°F and potatoes are fork-tender.', timerMin: 32 },
      { step: 5, text: 'Rest 5 minutes. Shower with parsley. Serve from the pan.' },
    ],
    tips: 'Want it crispier? Broil 2 minutes at the end. Watch closely.',
    storageNotes: 'Refrigerate up to 4 days in a sealed container.',
    freezerNotes: 'Chicken freezes well; potatoes turn grainy. Freeze chicken only.',
    nutrition: { calories: 520, fatG: 32, satFatG: 8, carbsG: 28, sugarG: 2, fiberG: 4, proteinG: 34, sodiumMg: 720 },
    costPerServingUsd: 3.85,
    dietaryTags: ['gluten-free', 'dairy-free'],
    allergenTags: [],
    keywords: ['one pan chicken', 'sheet pan dinner', 'lemon chicken', 'easy weeknight', 'mediterranean'],
    faq: [
      { q: 'Can I use boneless chicken thighs?', a: 'Yes — reduce cook time to 22–25 minutes. Bone-in stays juicier under high heat but boneless works fine for a faster weeknight version.' },
      { q: 'What sides go with this?', a: 'The potatoes are built in. Add a simple arugula salad with lemon vinaigrette or a Greek-style cucumber yogurt to balance the richness.' },
      { q: 'Can I make this dairy-free and gluten-free?', a: 'It already is. Every ingredient in this recipe is naturally gluten and dairy free.' },
    ],
  },
  {
    ...base('15-minute-garlic-butter-shrimp-pasta'),
    title: '15-Minute Garlic Butter Shrimp Pasta',
    description:
      'Buttery garlic shrimp tossed with linguine, lemon, and chili flakes — the pasta you make when you forgot to plan dinner and want to look like you did.',
    heroImage: null,
    galleryImages: [],
    videoUrl: null,
    prepTimeMin: 5,
    cookTimeMin: 10,
    totalTimeMin: 15,
    servings: 4,
    difficulty: 'easy',
    cuisine: 'italian',
    course: 'dinner',
    occasion: 'weeknight',
    equipment: ['Large skillet', 'Pasta pot'],
    ingredients: [
      { name: 'linguine', qty: 12, unit: 'oz' },
      { name: 'large shrimp, peeled and deveined', qty: 1, unit: 'lb' },
      { name: 'unsalted butter', qty: 4, unit: 'tbsp' },
      { name: 'garlic cloves, minced', qty: 5, unit: 'cloves' },
      { name: 'red pepper flakes', qty: 0.5, unit: 'tsp' },
      { name: 'lemon, juiced and zested', qty: 1, unit: 'whole' },
      { name: 'fresh parsley, chopped', qty: 0.25, unit: 'cup' },
      { name: 'kosher salt', qty: 1, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, text: 'Boil salted water and cook pasta to one minute under package directions. Reserve 1 cup pasta water before draining.' },
      { step: 2, text: 'Melt butter in a large skillet over medium heat. Add garlic and chili flakes, cook 30 seconds — do not brown.' },
      { step: 3, text: 'Add shrimp in a single layer. Cook 90 seconds per side until pink and just opaque.' },
      { step: 4, text: 'Add drained pasta, lemon juice, zest, and ½ cup pasta water. Toss until glossy. Splash more water if dry.' },
      { step: 5, text: 'Off heat: parsley and salt. Taste and adjust. Serve immediately.' },
    ],
    tips: 'Overcooked shrimp is rubbery and sad. Pull them the moment they curl into a C — beyond that is overcooked.',
    storageNotes: 'Best eaten fresh. Refrigerate up to 2 days; shrimp gets tough reheated.',
    freezerNotes: 'Do not freeze.',
    nutrition: { calories: 480, fatG: 16, satFatG: 8, carbsG: 58, sugarG: 2, fiberG: 3, proteinG: 28, sodiumMg: 680 },
    costPerServingUsd: 4.5,
    dietaryTags: [],
    allergenTags: ['shellfish', 'gluten', 'dairy'],
    keywords: ['shrimp pasta', '15 minute dinner', 'garlic butter shrimp', 'quick pasta', 'italian'],
    faq: [
      { q: 'Can I use frozen shrimp?', a: 'Yes. Thaw under cold running water for 5 minutes and pat very dry. Wet shrimp will steam instead of sear.' },
      { q: 'Is this gluten-free with rice pasta?', a: 'Yes, swap linguine for a gluten-free pasta and use the pasta water trick the same way. Texture is excellent.' },
    ],
  },
  {
    ...base('weeknight-chickpea-coconut-curry'),
    title: 'Weeknight Chickpea Coconut Curry',
    description:
      'A creamy, deeply spiced one-pot curry built from pantry staples. Vegan, gluten-free, freezer-friendly, and somehow tastes like it simmered all day.',
    heroImage: null,
    galleryImages: [],
    videoUrl: null,
    prepTimeMin: 10,
    cookTimeMin: 25,
    totalTimeMin: 35,
    servings: 4,
    difficulty: 'easy',
    cuisine: 'indian',
    course: 'dinner',
    occasion: 'weeknight',
    equipment: ['Dutch oven or large pot'],
    ingredients: [
      { name: 'olive oil', qty: 2, unit: 'tbsp' },
      { name: 'yellow onion, diced', qty: 1, unit: 'whole' },
      { name: 'garlic cloves, minced', qty: 4, unit: 'cloves' },
      { name: 'fresh ginger, grated', qty: 1, unit: 'tbsp' },
      { name: 'curry powder', qty: 2, unit: 'tbsp' },
      { name: 'ground cumin', qty: 1, unit: 'tsp' },
      { name: 'turmeric', qty: 0.5, unit: 'tsp' },
      { name: 'canned chickpeas, drained', qty: 2, unit: '15-oz cans' },
      { name: 'diced tomatoes', qty: 1, unit: '14-oz can' },
      { name: 'full-fat coconut milk', qty: 1, unit: '13.5-oz can' },
      { name: 'baby spinach', qty: 4, unit: 'cups' },
      { name: 'kosher salt', qty: 1, unit: 'tsp' },
      { name: 'lime, juiced', qty: 1, unit: 'whole' },
    ],
    instructions: [
      { step: 1, text: 'Warm oil in a Dutch oven over medium heat. Sweat onion 5 minutes until soft and translucent.' },
      { step: 2, text: 'Add garlic, ginger, and all spices. Stir 1 minute until intensely fragrant — this blooms the flavors.' },
      { step: 3, text: 'Add chickpeas and tomatoes. Simmer 5 minutes to start melting the spice into the sauce.' },
      { step: 4, text: 'Pour in coconut milk and salt. Simmer uncovered 12 minutes until thick enough to coat a spoon.', timerMin: 12 },
      { step: 5, text: 'Stir in spinach until just wilted. Off heat. Add lime juice. Taste and adjust salt.' },
      { step: 6, text: 'Serve over rice or with naan. Top with cilantro if you have it.' },
    ],
    tips: 'For deeper flavor: toast whole cumin and coriander seeds and grind fresh. Worth the extra 3 minutes.',
    storageNotes: 'Refrigerate up to 5 days. Flavor improves overnight.',
    freezerNotes: 'Freezes beautifully for 3 months. Thaw overnight in the fridge.',
    nutrition: { calories: 410, fatG: 22, satFatG: 14, carbsG: 42, sugarG: 8, fiberG: 12, proteinG: 13, sodiumMg: 690 },
    costPerServingUsd: 2.2,
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'],
    allergenTags: [],
    keywords: ['chickpea curry', 'coconut curry', 'vegan dinner', 'one pot meal', 'meal prep'],
    faq: [
      { q: 'Can I use light coconut milk?', a: 'You can but the sauce will be thinner and less luxurious. Full-fat is worth it. Add a teaspoon of cornstarch slurry if you go light.' },
      { q: 'How spicy is this?', a: 'Mild. Add cayenne or fresh chili to taste. Curry powder is a blend; the heat varies by brand.' },
      { q: 'Can I add chicken or paneer?', a: 'Yes. Brown 1 lb diced chicken before the onions and continue. For paneer, add 8 oz cubed in the last 5 minutes.' },
    ],
  },
  {
    ...base('crispy-baked-falafel'),
    title: 'Crispy Baked Falafel',
    description:
      'Herby, crunchy, properly seasoned falafel from dried chickpeas — no deep fryer, no soggy interior. The version that converts skeptics.',
    heroImage: null,
    galleryImages: [],
    videoUrl: null,
    prepTimeMin: 20,
    cookTimeMin: 25,
    totalTimeMin: 45,
    servings: 4,
    difficulty: 'medium',
    cuisine: 'middle-eastern',
    course: 'lunch',
    occasion: 'meal-prep',
    equipment: ['Food processor', 'Baking sheet'],
    ingredients: [
      { name: 'dried chickpeas, soaked 24 hours', qty: 1, unit: 'cup' },
      { name: 'yellow onion, roughly chopped', qty: 0.5, unit: 'whole' },
      { name: 'garlic cloves', qty: 4, unit: 'cloves' },
      { name: 'fresh parsley', qty: 1, unit: 'cup' },
      { name: 'fresh cilantro', qty: 0.5, unit: 'cup' },
      { name: 'ground cumin', qty: 1.5, unit: 'tsp' },
      { name: 'ground coriander', qty: 1, unit: 'tsp' },
      { name: 'baking soda', qty: 0.5, unit: 'tsp' },
      { name: 'kosher salt', qty: 1, unit: 'tsp' },
      { name: 'olive oil, for brushing', qty: 3, unit: 'tbsp' },
    ],
    instructions: [
      { step: 1, text: 'Drain soaked chickpeas. Do NOT use canned — they have too much moisture and the falafel falls apart.' },
      { step: 2, text: 'Pulse chickpeas, onion, garlic, herbs, spices, baking soda, and salt in a food processor until coarse but cohesive — like wet sand.' },
      { step: 3, text: 'Chill mixture 30 minutes. This helps it hold shape.' },
      { step: 4, text: 'Heat oven to 425°F (220°C). Line a sheet pan with parchment.' },
      { step: 5, text: 'Form 16 small patties (2 tbsp each). Brush generously with olive oil on both sides.' },
      { step: 6, text: 'Bake 12 minutes, flip, bake 10 more until deeply golden.', timerMin: 22 },
      { step: 7, text: 'Serve with tahini sauce, warm pita, tomatoes, cucumbers, pickled onions.' },
    ],
    tips: 'Skip the soaking step and the falafel will be gummy and dense. There is no shortcut here that works.',
    storageNotes: 'Refrigerate cooked falafel up to 4 days. Reheat in a 375°F oven 6 minutes to re-crisp.',
    freezerNotes: 'Freeze raw shaped patties on a tray, then bag. Bake from frozen, add 5 minutes.',
    nutrition: { calories: 320, fatG: 12, satFatG: 1.5, carbsG: 42, sugarG: 5, fiberG: 11, proteinG: 13, sodiumMg: 680 },
    costPerServingUsd: 1.85,
    dietaryTags: ['vegan', 'vegetarian', 'dairy-free'],
    allergenTags: [],
    keywords: ['baked falafel', 'middle eastern', 'vegan protein', 'meal prep', 'chickpea recipe'],
    faq: [
      { q: 'Can I use canned chickpeas?', a: 'Strongly not recommended. Canned chickpeas are cooked and hold too much water, causing the falafel to crumble or turn gummy. Dried, soaked is the right move.' },
      { q: 'Why baking soda?', a: 'It tenderizes the chickpea proteins so the interior is light, not dense. Half a teaspoon is enough.' },
    ],
  },
  {
    ...base('5-ingredient-banana-oat-pancakes'),
    title: '5-Ingredient Banana Oat Pancakes',
    description:
      'Fluffy, naturally sweet pancakes from pantry staples — no flour, no refined sugar, ready in fifteen minutes. Kid-approved breakfast champion.',
    heroImage: null,
    galleryImages: [],
    videoUrl: null,
    prepTimeMin: 5,
    cookTimeMin: 10,
    totalTimeMin: 15,
    servings: 2,
    difficulty: 'easy',
    cuisine: 'american',
    course: 'breakfast',
    occasion: 'weeknight',
    equipment: ['Blender', 'Non-stick skillet'],
    ingredients: [
      { name: 'ripe bananas', qty: 2, unit: 'medium' },
      { name: 'rolled oats', qty: 1, unit: 'cup' },
      { name: 'eggs', qty: 2, unit: 'large' },
      { name: 'baking powder', qty: 1, unit: 'tsp' },
      { name: 'vanilla extract', qty: 1, unit: 'tsp' },
      { name: 'butter or oil, for cooking', qty: 1, unit: 'tbsp' },
    ],
    instructions: [
      { step: 1, text: 'Blend all ingredients until smooth, about 30 seconds. Batter should be pourable but thick.' },
      { step: 2, text: 'Heat a non-stick skillet over medium-low. Melt butter to coat.' },
      { step: 3, text: 'Pour ¼-cup pools. Cook 2 minutes until bubbles form and edges look dry.' },
      { step: 4, text: 'Flip carefully — these are more delicate than regular pancakes. Cook 90 seconds more.' },
      { step: 5, text: 'Stack and top with berries, maple syrup, or peanut butter.' },
    ],
    tips: 'Bananas must be ripe — brown-spotted ripe. Green bananas make pasty, bitter pancakes.',
    storageNotes: 'Refrigerate up to 3 days. Reheat in a toaster for crisp edges.',
    freezerNotes: 'Stack with parchment between each. Freeze 2 months. Toast from frozen.',
    nutrition: { calories: 330, fatG: 10, satFatG: 4, carbsG: 50, sugarG: 16, fiberG: 6, proteinG: 12, sodiumMg: 220 },
    costPerServingUsd: 0.95,
    dietaryTags: ['vegetarian', 'gluten-free'],
    allergenTags: ['egg', 'dairy'],
    keywords: ['banana pancakes', 'oat pancakes', 'healthy breakfast', 'gluten free pancakes', '5 ingredient'],
    faq: [
      { q: 'Can I make these vegan?', a: 'Sub each egg with 1 tbsp ground flax + 3 tbsp water, rested 5 minutes. Texture is slightly denser but still very good.' },
      { q: 'Are these truly gluten-free?', a: 'Yes if you use certified gluten-free oats. Regular oats are often cross-contaminated.' },
    ],
  },
  {
    ...base('30-minute-thai-basil-chicken'),
    title: '30-Minute Thai Basil Chicken (Pad Krapow)',
    description:
      'The Bangkok street food classic in under thirty minutes — fragrant basil, garlic, chili, and crispy fried egg on top. Bold, fast, addictive.',
    heroImage: null,
    galleryImages: [],
    videoUrl: null,
    prepTimeMin: 10,
    cookTimeMin: 12,
    totalTimeMin: 22,
    servings: 4,
    difficulty: 'easy',
    cuisine: 'thai',
    course: 'dinner',
    occasion: 'weeknight',
    equipment: ['Wok or large skillet'],
    ingredients: [
      { name: 'ground chicken (or pork)', qty: 1, unit: 'lb' },
      { name: 'garlic cloves, minced', qty: 6, unit: 'cloves' },
      { name: 'Thai chilies, minced', qty: 3, unit: 'whole' },
      { name: 'shallots, sliced', qty: 2, unit: 'whole' },
      { name: 'oyster sauce', qty: 2, unit: 'tbsp' },
      { name: 'soy sauce', qty: 1, unit: 'tbsp' },
      { name: 'fish sauce', qty: 1, unit: 'tbsp' },
      { name: 'sugar', qty: 1, unit: 'tsp' },
      { name: 'Thai holy basil (or sweet basil)', qty: 1, unit: 'cup, packed' },
      { name: 'neutral oil', qty: 2, unit: 'tbsp' },
      { name: 'eggs', qty: 4, unit: 'large' },
      { name: 'cooked jasmine rice, for serving', qty: 4, unit: 'cups' },
    ],
    instructions: [
      { step: 1, text: 'Pound garlic and chili in a mortar to a rough paste (or pulse in a mini food processor).' },
      { step: 2, text: 'Heat 1 tbsp oil in a wok over high heat. Add garlic-chili paste and shallots, stir 30 seconds.' },
      { step: 3, text: 'Add chicken. Break apart and cook until no pink remains, about 4 minutes.' },
      { step: 4, text: 'Add oyster, soy, fish sauce, and sugar. Stir-fry 1 minute to glaze.' },
      { step: 5, text: 'Off heat, fold in basil until just wilted. Set aside.' },
      { step: 6, text: 'In a separate skillet, fry eggs in remaining oil over high heat until edges are crispy and yolk is runny.' },
      { step: 7, text: 'Serve chicken over rice with the fried egg on top. Break the yolk and stir in.' },
    ],
    tips: 'Thai holy basil is more peppery than Italian sweet basil. Sweet basil works in a pinch but the dish is sweeter and less herbaceous.',
    storageNotes: 'Refrigerate chicken mixture up to 3 days. Fry eggs fresh each time.',
    freezerNotes: 'Freeze chicken mixture up to 2 months.',
    nutrition: { calories: 480, fatG: 22, satFatG: 6, carbsG: 38, sugarG: 4, fiberG: 1, proteinG: 32, sodiumMg: 1280 },
    costPerServingUsd: 3.4,
    dietaryTags: ['dairy-free'],
    allergenTags: ['egg', 'fish', 'soy'],
    keywords: ['pad krapow', 'thai basil chicken', 'thai street food', '30 minute dinner', 'stir fry'],
    faq: [
      { q: 'Where do I find Thai holy basil?', a: 'Asian grocery stores or Asian section of larger supermarkets. Italian sweet basil works as a substitute but the flavor profile changes.' },
      { q: 'How spicy is this?', a: 'As spicy as you want. Three Thai chilies is medium-hot. Use one for mild, six for authentic Bangkok heat.' },
    ],
  },
  {
    ...base('classic-chocolate-chip-cookies'),
    title: 'Chewy Brown Butter Chocolate Chip Cookies',
    description:
      'Crisp edges, gooey centers, deep nutty flavor from browned butter — the cookie that ruins all other cookies. Worth the extra step.',
    heroImage: null,
    galleryImages: [],
    videoUrl: null,
    prepTimeMin: 15,
    cookTimeMin: 12,
    totalTimeMin: 27,
    servings: 18,
    difficulty: 'medium',
    cuisine: 'american',
    course: 'dessert',
    occasion: 'weekend',
    equipment: ['Saucepan', 'Mixing bowls', 'Baking sheet'],
    ingredients: [
      { name: 'unsalted butter', qty: 1, unit: 'cup' },
      { name: 'dark brown sugar', qty: 1, unit: 'cup' },
      { name: 'granulated sugar', qty: 0.5, unit: 'cup' },
      { name: 'eggs', qty: 2, unit: 'large' },
      { name: 'vanilla extract', qty: 2, unit: 'tsp' },
      { name: 'all-purpose flour', qty: 2.25, unit: 'cups' },
      { name: 'baking soda', qty: 1, unit: 'tsp' },
      { name: 'kosher salt', qty: 1, unit: 'tsp' },
      { name: 'semisweet chocolate chunks', qty: 2, unit: 'cups' },
      { name: 'flaky sea salt, for topping', qty: 1, unit: 'pinch' },
    ],
    instructions: [
      { step: 1, text: 'In a saucepan, melt butter over medium heat. Continue cooking, swirling, until amber and nutty smelling, 5–7 minutes. Pour into a heatproof bowl. Cool 15 minutes.' },
      { step: 2, text: 'Whisk both sugars into the cooled butter. Add eggs and vanilla. Whisk vigorously 1 minute until glossy.' },
      { step: 3, text: 'Fold in flour, baking soda, and salt until just combined. Fold in chocolate.' },
      { step: 4, text: 'Chill dough at least 1 hour (or overnight for deeper flavor).' },
      { step: 5, text: 'Heat oven to 375°F (190°C). Line baking sheets with parchment.' },
      { step: 6, text: 'Scoop 3-tbsp balls onto sheets, 2 inches apart. Bake 11–12 minutes until edges are set but centers look underdone.', timerMin: 11 },
      { step: 7, text: 'Tap pan on counter twice to flatten centers. Sprinkle with flaky salt. Cool 5 minutes on the sheet before moving.' },
    ],
    tips: 'The chill is non-negotiable. Skipping it = thin, greasy cookies. Overnight chill = chef-tier cookies.',
    storageNotes: 'Airtight at room temperature 4 days. A piece of bread in the container keeps them soft.',
    freezerNotes: 'Freeze raw dough balls for 3 months. Bake from frozen, add 2 minutes.',
    nutrition: { calories: 240, fatG: 12, satFatG: 7, carbsG: 31, sugarG: 21, fiberG: 1, proteinG: 3, sodiumMg: 180 },
    costPerServingUsd: 0.4,
    dietaryTags: ['vegetarian'],
    allergenTags: ['gluten', 'dairy', 'egg'],
    keywords: ['chocolate chip cookies', 'brown butter cookies', 'best chocolate chip cookies', 'chewy cookies'],
    faq: [
      { q: 'Why brown the butter?', a: 'Browning develops nutty, caramel-like compounds and removes water, concentrating flavor. The difference is night and day.' },
      { q: 'Can I skip the chill?', a: 'Technically yes, practically no. The dough needs to rehydrate the flour and let the butter re-solidify. Chilled dough = perfect texture.' },
    ],
  },
  {
    ...base('smashed-cucumber-salad'),
    title: 'Smashed Cucumber Salad with Chili Crisp',
    description:
      'Crunchy, garlicky, spicy cucumber salad you can throw together in ten minutes — the side dish that steals the meal.',
    heroImage: null,
    galleryImages: [],
    videoUrl: null,
    prepTimeMin: 10,
    cookTimeMin: 0,
    totalTimeMin: 10,
    servings: 4,
    difficulty: 'easy',
    cuisine: 'chinese',
    course: 'side',
    occasion: 'summer',
    equipment: ['Rolling pin or heavy pan'],
    ingredients: [
      { name: 'Persian or English cucumbers', qty: 1.5, unit: 'lb' },
      { name: 'kosher salt', qty: 1, unit: 'tsp' },
      { name: 'garlic cloves, grated', qty: 3, unit: 'cloves' },
      { name: 'soy sauce', qty: 2, unit: 'tbsp' },
      { name: 'rice vinegar', qty: 2, unit: 'tbsp' },
      { name: 'sesame oil', qty: 1, unit: 'tbsp' },
      { name: 'chili crisp', qty: 1, unit: 'tbsp' },
      { name: 'sugar', qty: 1, unit: 'tsp' },
      { name: 'toasted sesame seeds', qty: 1, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, text: 'Place cucumbers on a cutting board. Smash with a rolling pin or flat pan until they split. Tear into rough 2-inch chunks.' },
      { step: 2, text: 'Toss with salt and let drain in a colander 10 minutes. This draws out water for crunch.' },
      { step: 3, text: 'Whisk garlic, soy, vinegar, sesame oil, chili crisp, and sugar in a bowl.' },
      { step: 4, text: 'Press cucumbers gently to release more water. Toss with dressing.' },
      { step: 5, text: 'Top with sesame seeds. Serve immediately or chill up to 1 hour.' },
    ],
    tips: 'Smashing creates more surface area than slicing — the dressing clings far better.',
    storageNotes: 'Best within 2 hours. Cucumbers weep over time.',
    freezerNotes: 'Do not freeze.',
    nutrition: { calories: 80, fatG: 5, satFatG: 0.5, carbsG: 8, sugarG: 4, fiberG: 1, proteinG: 2, sodiumMg: 580 },
    costPerServingUsd: 1.1,
    dietaryTags: ['vegan', 'vegetarian', 'dairy-free'],
    allergenTags: ['soy', 'sesame'],
    keywords: ['smashed cucumber', 'chili crisp salad', 'asian salad', 'quick side dish', 'cold salad'],
    faq: [
      { q: 'No chili crisp on hand?', a: 'Sub red pepper flakes plus an extra teaspoon of sesame oil. Different vibe but still excellent.' },
      { q: 'Gluten-free version?', a: 'Swap soy sauce for tamari and verify your chili crisp is GF (Lao Gan Ma is).' },
    ],
  },
  {
    ...base('creamy-tomato-tortellini-soup'),
    title: 'Creamy Tomato Tortellini Soup',
    description:
      'Comfort-in-a-bowl with cheese tortellini, basil, and a velvety tomato broth — twenty-five minutes from pantry to spoon.',
    heroImage: null,
    galleryImages: [],
    videoUrl: null,
    prepTimeMin: 5,
    cookTimeMin: 20,
    totalTimeMin: 25,
    servings: 4,
    difficulty: 'easy',
    cuisine: 'italian',
    course: 'dinner',
    occasion: 'comfort-food',
    equipment: ['Large pot'],
    ingredients: [
      { name: 'olive oil', qty: 2, unit: 'tbsp' },
      { name: 'yellow onion, diced', qty: 1, unit: 'whole' },
      { name: 'garlic cloves, minced', qty: 4, unit: 'cloves' },
      { name: 'tomato paste', qty: 2, unit: 'tbsp' },
      { name: 'Italian seasoning', qty: 1, unit: 'tbsp' },
      { name: 'crushed tomatoes', qty: 1, unit: '28-oz can' },
      { name: 'vegetable or chicken broth', qty: 4, unit: 'cups' },
      { name: 'cheese tortellini', qty: 9, unit: 'oz' },
      { name: 'heavy cream', qty: 0.5, unit: 'cup' },
      { name: 'fresh basil, torn', qty: 0.25, unit: 'cup' },
      { name: 'kosher salt', qty: 1, unit: 'tsp' },
      { name: 'black pepper', qty: 0.5, unit: 'tsp' },
      { name: 'grated parmesan, for serving', qty: 0.5, unit: 'cup' },
    ],
    instructions: [
      { step: 1, text: 'Heat oil in a large pot. Sweat onion 5 minutes. Add garlic, cook 30 seconds.' },
      { step: 2, text: 'Stir in tomato paste and Italian seasoning. Cook 1 minute until paste darkens — this deepens flavor.' },
      { step: 3, text: 'Add crushed tomatoes and broth. Bring to a simmer.' },
      { step: 4, text: 'Add tortellini. Simmer 7–9 minutes per package directions.', timerMin: 8 },
      { step: 5, text: 'Stir in cream and basil. Heat through but do not boil — cream can split.' },
      { step: 6, text: 'Season with salt and pepper. Ladle into bowls, top with parmesan.' },
    ],
    tips: 'For deeper flavor: add a parmesan rind while the broth simmers. Fish it out before serving.',
    storageNotes: 'Refrigerate 3 days. Tortellini absorbs liquid — add splash of broth when reheating.',
    freezerNotes: 'Freeze without pasta. Add fresh tortellini when reheating.',
    nutrition: { calories: 460, fatG: 22, satFatG: 11, carbsG: 48, sugarG: 12, fiberG: 5, proteinG: 16, sodiumMg: 1180 },
    costPerServingUsd: 3.1,
    dietaryTags: ['vegetarian'],
    allergenTags: ['gluten', 'dairy', 'egg'],
    keywords: ['tortellini soup', 'tomato soup', 'creamy pasta soup', 'italian comfort food', '30 minute soup'],
    faq: [
      { q: 'Can I make it dairy-free?', a: 'Swap heavy cream for full-fat coconut milk (savory result is great) or a cashew cream. Skip parmesan or use a nutritional yeast topping.' },
      { q: 'Why tomato paste?', a: 'Tomato paste is concentrated umami. Cooking it briefly with the aromatics builds depth that just crushed tomatoes alone cannot.' },
    ],
  },
  {
    ...base('miso-glazed-salmon-bowls'),
    title: 'Miso-Glazed Salmon Rice Bowls',
    description:
      'Sweet-savory miso-glazed salmon over rice with quick-pickled cucumbers and edamame. Restaurant-quality in twenty-five minutes.',
    heroImage: null,
    galleryImages: [],
    videoUrl: null,
    prepTimeMin: 10,
    cookTimeMin: 15,
    totalTimeMin: 25,
    servings: 4,
    difficulty: 'easy',
    cuisine: 'japanese',
    course: 'dinner',
    occasion: 'weeknight',
    equipment: ['Sheet pan', 'Small saucepan'],
    ingredients: [
      { name: 'salmon fillets, skin-on', qty: 4, unit: '6-oz pieces' },
      { name: 'white miso paste', qty: 3, unit: 'tbsp' },
      { name: 'mirin', qty: 2, unit: 'tbsp' },
      { name: 'soy sauce', qty: 1, unit: 'tbsp' },
      { name: 'honey', qty: 1, unit: 'tbsp' },
      { name: 'rice vinegar', qty: 1, unit: 'tbsp' },
      { name: 'cooked short-grain rice', qty: 4, unit: 'cups' },
      { name: 'cucumber, thinly sliced', qty: 1, unit: 'whole' },
      { name: 'frozen edamame, thawed', qty: 1, unit: 'cup' },
      { name: 'green onions, sliced', qty: 3, unit: 'whole' },
      { name: 'toasted sesame seeds', qty: 1, unit: 'tbsp' },
    ],
    instructions: [
      { step: 1, text: 'Whisk miso, mirin, soy, and honey in a small bowl until smooth.' },
      { step: 2, text: 'Heat broiler. Line a sheet pan with foil.' },
      { step: 3, text: 'Pat salmon dry. Place on sheet pan. Brush thick layer of glaze on top.' },
      { step: 4, text: 'Broil 6–8 minutes until glaze caramelizes and salmon flakes. Watch closely — miso burns fast.', timerMin: 7 },
      { step: 5, text: 'Meanwhile, toss cucumbers with rice vinegar and a pinch of salt. Let pickle 5 minutes.' },
      { step: 6, text: 'Build bowls: rice, salmon, cucumbers, edamame. Shower with green onions and sesame seeds.' },
    ],
    tips: 'Miso burns quickly under direct heat. Place the rack one notch below the top, not the highest position.',
    storageNotes: 'Refrigerate components separately up to 2 days.',
    freezerNotes: 'Do not freeze cooked salmon.',
    nutrition: { calories: 590, fatG: 22, satFatG: 4, carbsG: 60, sugarG: 10, fiberG: 5, proteinG: 38, sodiumMg: 980 },
    costPerServingUsd: 5.8,
    dietaryTags: ['dairy-free'],
    allergenTags: ['fish', 'soy', 'sesame'],
    keywords: ['miso salmon', 'salmon bowls', 'japanese rice bowl', 'easy salmon recipe', 'weeknight dinner'],
    faq: [
      { q: 'No mirin?', a: 'Sub 1 tbsp dry sherry plus ½ tsp sugar, or just 1 tbsp rice vinegar plus ½ tsp sugar.' },
      { q: 'Is this gluten-free?', a: 'With tamari instead of soy sauce, and verifying your miso paste (most are GF), yes.' },
    ],
  },
  {
    ...base('jollof-rice'),
    title: 'West African Jollof Rice',
    description:
      'Smoky, deeply flavored one-pot rice with tomato, scotch bonnet, and bay — the dish that starts arguments in every African household, here in its simplest weeknight form.',
    heroImage: null,
    galleryImages: [],
    videoUrl: null,
    prepTimeMin: 15,
    cookTimeMin: 40,
    totalTimeMin: 55,
    servings: 6,
    difficulty: 'medium',
    cuisine: 'west-african',
    course: 'dinner',
    occasion: 'weekend',
    equipment: ['Heavy pot or Dutch oven', 'Blender'],
    ingredients: [
      { name: 'long-grain parboiled rice', qty: 2.5, unit: 'cups' },
      { name: 'red bell peppers', qty: 3, unit: 'whole' },
      { name: 'plum tomatoes', qty: 4, unit: 'whole' },
      { name: 'scotch bonnet pepper', qty: 1, unit: 'whole' },
      { name: 'yellow onions', qty: 2, unit: 'whole' },
      { name: 'tomato paste', qty: 3, unit: 'tbsp' },
      { name: 'neutral oil', qty: 0.33, unit: 'cup' },
      { name: 'garlic cloves, minced', qty: 4, unit: 'cloves' },
      { name: 'fresh ginger, grated', qty: 1, unit: 'tbsp' },
      { name: 'curry powder', qty: 1, unit: 'tbsp' },
      { name: 'dried thyme', qty: 1, unit: 'tsp' },
      { name: 'bay leaves', qty: 3, unit: 'whole' },
      { name: 'chicken or vegetable stock', qty: 2.5, unit: 'cups' },
      { name: 'kosher salt', qty: 1.5, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, text: 'Blend bell peppers, tomatoes, scotch bonnet, and 1 onion until smooth. Pour into a pot and simmer 15 minutes to reduce by a third.' },
      { step: 2, text: 'Rinse rice in cold water until water runs clear. Drain.' },
      { step: 3, text: 'In a heavy pot, heat oil. Dice the second onion and sauté 5 minutes until soft.' },
      { step: 4, text: 'Add garlic, ginger, curry powder, thyme. Toast 1 minute.' },
      { step: 5, text: 'Stir in tomato paste, cook 2 minutes. Add reduced pepper-tomato mixture and bay leaves. Simmer 10 minutes until oil pools on top.', timerMin: 10 },
      { step: 6, text: 'Add rice and stock. Stir once. Cover tightly. Reduce heat to lowest setting.' },
      { step: 7, text: 'Cook 20 minutes without lifting the lid. Check rice; if not tender, cook 5 more.', timerMin: 20 },
      { step: 8, text: 'Off heat, rest covered 10 minutes. Fluff. Discard bay leaves.' },
    ],
    tips: 'The bottom should form a smoky crust ("party rice"). Do not stir while cooking — let the heat do its work.',
    storageNotes: 'Refrigerate 4 days. Reheats well with a splash of water.',
    freezerNotes: 'Freezes 2 months. Reheat covered with water added.',
    nutrition: { calories: 380, fatG: 11, satFatG: 1.5, carbsG: 64, sugarG: 8, fiberG: 4, proteinG: 7, sodiumMg: 720 },
    costPerServingUsd: 1.45,
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'],
    allergenTags: [],
    keywords: ['jollof rice', 'west african jollof', 'nigerian rice', 'one pot rice', 'african cuisine'],
    faq: [
      { q: 'Can I use basmati instead of parboiled rice?', a: 'You can, but parboiled holds up to long simmering without turning mushy. Basmati needs less liquid and a shorter cook.' },
      { q: 'Too spicy?', a: 'Use half a scotch bonnet, or substitute habanero (similar) or jalapeño (much milder).' },
    ],
  },
  {
    ...base('30-minute-veggie-fried-rice'),
    title: '30-Minute Veggie Fried Rice',
    description:
      'Better than takeout — crispy edges, perfectly seasoned, and built from whatever vegetables are wilting in your fridge.',
    heroImage: null,
    galleryImages: [],
    videoUrl: null,
    prepTimeMin: 10,
    cookTimeMin: 12,
    totalTimeMin: 22,
    servings: 4,
    difficulty: 'easy',
    cuisine: 'chinese',
    course: 'dinner',
    occasion: 'weeknight',
    equipment: ['Wok or large skillet'],
    ingredients: [
      { name: 'cold cooked jasmine rice (day-old ideal)', qty: 4, unit: 'cups' },
      { name: 'eggs, beaten', qty: 3, unit: 'large' },
      { name: 'neutral oil', qty: 3, unit: 'tbsp' },
      { name: 'garlic cloves, minced', qty: 4, unit: 'cloves' },
      { name: 'frozen mixed vegetables (peas, carrots, corn)', qty: 1.5, unit: 'cups' },
      { name: 'green onions, sliced', qty: 4, unit: 'whole' },
      { name: 'soy sauce', qty: 3, unit: 'tbsp' },
      { name: 'oyster sauce', qty: 1, unit: 'tbsp' },
      { name: 'toasted sesame oil', qty: 1, unit: 'tsp' },
      { name: 'white pepper', qty: 0.25, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, text: 'Heat 1 tbsp oil in a wok over high heat. Pour in eggs, scramble quickly, transfer to a plate.' },
      { step: 2, text: 'Add remaining oil. Toss in garlic, stir 15 seconds.' },
      { step: 3, text: 'Add frozen vegetables. Stir-fry 2 minutes until heated through.' },
      { step: 4, text: 'Add cold rice. Press to flatten. Let it sit 30 seconds to crisp. Toss. Repeat once.' },
      { step: 5, text: 'Drizzle soy sauce around the edge of the wok (it caramelizes there). Add oyster sauce, sesame oil, white pepper. Toss to coat.' },
      { step: 6, text: 'Return eggs. Add green onions. Toss 30 seconds. Serve immediately.' },
    ],
    tips: 'Day-old refrigerated rice is dryer and fries up with separate, crispy grains. Fresh rice turns mushy. Plan ahead.',
    storageNotes: 'Refrigerate 3 days. Reheats well in a skillet with a splash of water.',
    freezerNotes: 'Freezes 1 month. Texture suffers slightly.',
    nutrition: { calories: 380, fatG: 13, satFatG: 2.5, carbsG: 55, sugarG: 3, fiberG: 4, proteinG: 11, sodiumMg: 920 },
    costPerServingUsd: 1.65,
    dietaryTags: ['vegetarian', 'dairy-free'],
    allergenTags: ['egg', 'soy'],
    keywords: ['fried rice', 'vegetarian fried rice', '30 minute dinner', 'leftover rice recipe', 'asian dinner'],
    faq: [
      { q: 'No day-old rice?', a: 'Spread freshly cooked rice on a tray and chill in the freezer 30 minutes. Not perfect but workable.' },
      { q: 'How do I make it vegan?', a: 'Skip the eggs and use vegan oyster sauce (mushroom-based versions are widely available).' },
    ],
  },
];

export const SEED_COLLECTIONS = [
  {
    slug: '20-minute-dinners',
    title: '20-Minute Dinners',
    description: 'Fast weeknight meals that taste like you actually tried.',
    recipeSlugs: ['15-minute-garlic-butter-shrimp-pasta', '30-minute-thai-basil-chicken', '5-ingredient-banana-oat-pancakes', '30-minute-veggie-fried-rice'],
  },
  {
    slug: 'vegan-weeknights',
    title: 'Vegan Weeknights Under $3 a Serving',
    description: 'Hearty plant-based meals that fill the plate and the wallet.',
    recipeSlugs: ['weeknight-chickpea-coconut-curry', 'crispy-baked-falafel', 'smashed-cucumber-salad', 'jollof-rice'],
  },
  {
    slug: 'comfort-food-classics',
    title: 'Comfort Food Classics',
    description: 'The bowls and plates you crave on a Tuesday in February.',
    recipeSlugs: ['creamy-tomato-tortellini-soup', 'classic-chocolate-chip-cookies', 'one-pan-lemon-garlic-chicken'],
  },
];
